package lab5_miguelrojas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearHeroe = new javax.swing.JDialog();
        jtb_menuHeroe = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombreHeroe = new javax.swing.JTextField();
        tf_poderHeroe = new javax.swing.JTextField();
        tf_debilidadHeroe = new javax.swing.JTextField();
        js_fuerzaHeroe = new javax.swing.JSpinner();
        js_agilidadFisicaHeroe = new javax.swing.JSpinner();
        js_agilidadMentalHeroe = new javax.swing.JSpinner();
        jb_crearHeroe = new javax.swing.JButton();
        jd_crearVillano = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        js_fuerzaVillano = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        js_agilidadFisicaVillano = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        js_agilidadMentalVillano = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jb_crearVillano = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreVillano = new javax.swing.JTextField();
        tf_poderVillano = new javax.swing.JTextField();
        tf_debilidadVillano = new javax.swing.JTextField();
        jd_menuEscuadrones = new javax.swing.JDialog();
        jtp_menuEscuadron = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rb_superheroe = new javax.swing.JRadioButton();
        rb_villanos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        tf_nombreEscuadron = new javax.swing.JTextField();
        tf_lugarEscuadron = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_listaEscuadrones = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jb_modificarEscuadron = new javax.swing.JButton();
        jb_eliminarEscuadron = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jb_elegirLider = new javax.swing.JButton();
        jb_agregarMiembro = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_listaEscuadrones2 = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        bg_tipoEscuadron = new javax.swing.ButtonGroup();
        jd_modEscuadron = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rb_superheroeMod = new javax.swing.JRadioButton();
        rb_villanosMod = new javax.swing.JRadioButton();
        jb_modEscuadron = new javax.swing.JButton();
        tf_nombreEscuadronMod = new javax.swing.JTextField();
        tf_lugarEscuadronMod = new javax.swing.JTextField();
        bg_tipoEscuadronMod = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_menuHeroe = new javax.swing.JButton();
        jb_menuVillano = new javax.swing.JButton();
        jb_menuEscuadron = new javax.swing.JButton();
        jb_simulacion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaHeroes = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listaVillanos = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Crear Heroe");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Poder:");

        jLabel5.setText("Debilidad:");

        jLabel6.setText("Fuerza:");

        jLabel7.setText("Agilidad Fisica:");

        jLabel8.setText("Agilidad Mental:");

        js_fuerzaHeroe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        js_agilidadFisicaHeroe.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        js_agilidadMentalHeroe.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        jb_crearHeroe.setText("Crear Heroe");
        jb_crearHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearHeroeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_poderHeroe)
                                    .addComponent(tf_debilidadHeroe))
                                .addGap(74, 74, 74)))
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(js_agilidadMentalHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreHeroe)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(js_agilidadFisicaHeroe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_fuerzaHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_crearHeroe)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_fuerzaHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(tf_poderHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_agilidadFisicaHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(tf_debilidadHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_agilidadMentalHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jb_crearHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jtb_menuHeroe.addTab("Crear Heroe", jPanel2);

        javax.swing.GroupLayout jd_crearHeroeLayout = new javax.swing.GroupLayout(jd_crearHeroe.getContentPane());
        jd_crearHeroe.getContentPane().setLayout(jd_crearHeroeLayout);
        jd_crearHeroeLayout.setHorizontalGroup(
            jd_crearHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_menuHeroe)
        );
        jd_crearHeroeLayout.setVerticalGroup(
            jd_crearHeroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_menuHeroe)
        );

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Crear Villano");

        js_fuerzaVillano.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel13.setText("Nombre:");

        js_agilidadFisicaVillano.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        jLabel14.setText("Poder:");

        js_agilidadMentalVillano.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        jLabel15.setText("Debilidad:");

        jb_crearVillano.setText("Crear Villano");
        jb_crearVillano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearVillanoMouseClicked(evt);
            }
        });

        jLabel16.setText("Fuerza:");

        jLabel17.setText("Agilidad Fisica:");

        jLabel18.setText("Agilidad Mental:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreVillano, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(js_agilidadFisicaVillano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_fuerzaVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_poderVillano)
                                    .addComponent(tf_debilidadVillano))
                                .addGap(74, 74, 74)))
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(js_agilidadMentalVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_crearVillano)
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(tf_nombreVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_fuerzaVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(tf_poderVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_agilidadFisicaVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(tf_debilidadVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_agilidadMentalVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jb_crearVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearVillanoLayout = new javax.swing.GroupLayout(jd_crearVillano.getContentPane());
        jd_crearVillano.getContentPane().setLayout(jd_crearVillanoLayout);
        jd_crearVillanoLayout.setHorizontalGroup(
            jd_crearVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearVillanoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_crearVillanoLayout.setVerticalGroup(
            jd_crearVillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearVillanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtp_menuEscuadron.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtp_menuEscuadronStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setText("Crear Escuadron");

        jLabel20.setText("Nombre:");

        jLabel21.setText("Ubicación de base:");

        jLabel22.setText("Tipo de Escuadron:");

        bg_tipoEscuadron.add(rb_superheroe);
        rb_superheroe.setSelected(true);
        rb_superheroe.setText("Superheroes");

        bg_tipoEscuadron.add(rb_villanos);
        rb_villanos.setText("Villanos");

        jButton1.setText("Crear Escuadron");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rb_superheroe)
                                .addGap(18, 18, 18)
                                .addComponent(rb_villanos))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_lugarEscuadron, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(tf_nombreEscuadron, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_nombreEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_lugarEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_superheroe)
                        .addComponent(rb_villanos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jtp_menuEscuadron.addTab("Crear Escuadron", jPanel4);

        jScrollPane4.setViewportView(jl_listaEscuadrones);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel23.setText("Lista de Escuadrones");

        jb_modificarEscuadron.setText("Modificar");
        jb_modificarEscuadron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarEscuadronMouseClicked(evt);
            }
        });

        jb_eliminarEscuadron.setText("Eliminar");
        jb_eliminarEscuadron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarEscuadronMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_modificarEscuadron, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_eliminarEscuadron, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jb_modificarEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jb_eliminarEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jtp_menuEscuadron.addTab("Modificar/Eliminar Escuadron", jPanel5);

        jb_elegirLider.setText("Elegir Lider");
        jb_elegirLider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elegirLiderMouseClicked(evt);
            }
        });

        jb_agregarMiembro.setText("Agregar Miembro");
        jb_agregarMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMiembroMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportView(jl_listaEscuadrones2);

        jLabel28.setText("Lista de Escuadrones");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_agregarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_elegirLider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(116, 116, 116))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jb_elegirLider, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jb_agregarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jtp_menuEscuadron.addTab("Agregar Miembros", jPanel6);

        javax.swing.GroupLayout jd_menuEscuadronesLayout = new javax.swing.GroupLayout(jd_menuEscuadrones.getContentPane());
        jd_menuEscuadrones.getContentPane().setLayout(jd_menuEscuadronesLayout);
        jd_menuEscuadronesLayout.setHorizontalGroup(
            jd_menuEscuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuEscuadronesLayout.createSequentialGroup()
                .addComponent(jtp_menuEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_menuEscuadronesLayout.setVerticalGroup(
            jd_menuEscuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuEscuadronesLayout.createSequentialGroup()
                .addComponent(jtp_menuEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel24.setText("Modificar Escuadron");

        jLabel25.setText("Nombre:");

        jLabel26.setText("Ubicación de base:");

        jLabel27.setText("Tipo de Escuadron:");

        bg_tipoEscuadronMod.add(rb_superheroeMod);
        rb_superheroeMod.setSelected(true);
        rb_superheroeMod.setText("Superheroes");

        bg_tipoEscuadronMod.add(rb_villanosMod);
        rb_villanosMod.setText("Villanos");

        jb_modEscuadron.setText("Modificar Escuadron");
        jb_modEscuadron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modEscuadronMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modEscuadronLayout = new javax.swing.GroupLayout(jd_modEscuadron.getContentPane());
        jd_modEscuadron.getContentPane().setLayout(jd_modEscuadronLayout);
        jd_modEscuadronLayout.setHorizontalGroup(
            jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modEscuadronLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jd_modEscuadronLayout.createSequentialGroup()
                        .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(36, 36, 36)
                        .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modEscuadronLayout.createSequentialGroup()
                                .addComponent(rb_superheroeMod)
                                .addGap(18, 18, 18)
                                .addComponent(rb_villanosMod))
                            .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_lugarEscuadronMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(tf_nombreEscuadronMod, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modEscuadronLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_modEscuadron)
                .addGap(47, 47, 47))
        );
        jd_modEscuadronLayout.setVerticalGroup(
            jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modEscuadronLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addGap(52, 52, 52)
                .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_nombreEscuadronMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_lugarEscuadronMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jd_modEscuadronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_superheroeMod)
                        .addComponent(rb_villanosMod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jb_modEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Laboratorio5 Miguel Rojas");

        jb_menuHeroe.setText("Crear Heroe");
        jb_menuHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuHeroeMouseClicked(evt);
            }
        });

        jb_menuVillano.setText("Crear Villano");
        jb_menuVillano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuVillanoMouseClicked(evt);
            }
        });

        jb_menuEscuadron.setText("Menu Escuadrones");
        jb_menuEscuadron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuEscuadronMouseClicked(evt);
            }
        });

        jb_simulacion.setText("Simulacion");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Lista Superheroes");

        jScrollPane1.setViewportView(jl_listaHeroes);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Lista Villanos");

        jScrollPane2.setViewportView(jl_listaVillanos);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Arbol Escuadrones");

        jScrollPane3.setViewportView(jTree1);

        jButton5.setText("Modificar");

        jButton6.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_menuHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_menuVillano)
                                .addGap(47, 47, 47)
                                .addComponent(jb_menuEscuadron)
                                .addGap(47, 47, 47)
                                .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jButton5)
                                .addGap(56, 56, 56)
                                .addComponent(jButton6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_menuVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_menuHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_menuEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_menuHeroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuHeroeMouseClicked
        //Abrir menu de Heroes
        jd_crearHeroe.setModal(true);
        jd_crearHeroe.pack();
        jd_crearHeroe.setLocationRelativeTo(this);
        jd_crearHeroe.setVisible(true);
    }//GEN-LAST:event_jb_menuHeroeMouseClicked

    private void jb_crearHeroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearHeroeMouseClicked
        //Crear Heroe

        String nombre_heroe = null, poder_heroe = null, debilidad_heroe = null;
        int fuerza_heroe = 0, agilidad_fisicaH = 0, agilidad_mentalH = 0, suma_stats = 0;

        boolean crear = true;
        //Validar entrada de datos
        //Nombre
        if (tf_nombreHeroe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearHeroe, "Falta ingresar el nombre del heroe.");
            crear = false;
        } else {
            nombre_heroe = tf_nombreHeroe.getText();
        }
        //Poder

        if (tf_poderHeroe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearHeroe, "Falta ingresar el poder del heroe.");
            crear = false;
        } else {
            poder_heroe = tf_poderHeroe.getText();
        }

        //Debilidad
        if (tf_debilidadHeroe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearHeroe, "Falta ingresar la debilidad del heroe.");
            crear = false;
        } else {
            debilidad_heroe = tf_debilidadHeroe.getText();
        }

        //Fuerza
        fuerza_heroe = (int) js_fuerzaHeroe.getValue();
        //Agilidad Fisica
        agilidad_fisicaH = (int) js_agilidadFisicaHeroe.getValue();
        //Agilidad Mental
        agilidad_mentalH = (int) js_agilidadMentalHeroe.getValue();

        suma_stats = fuerza_heroe + agilidad_fisicaH + agilidad_mentalH;

        //Verificar estadisticas
        if (suma_stats != 100) {
            JOptionPane.showMessageDialog(jd_crearHeroe, "Las estadiscticas del superheroe no igualan a 100.\n"
                    + "No es capaz de ser un heroe.");
            crear = false;
            js_fuerzaHeroe.setValue(0);
            js_agilidadMentalHeroe.setValue(0);
            js_agilidadFisicaHeroe.setValue(0);
        }
        //Revisar nombre
        boolean verificar_nombre = true;
        for (int i = 0; i < lista_nombres.size(); i++) {
            if (lista_nombres.contains(nombre_heroe)) {
                verificar_nombre = false;
                break;
            }
        }

        if (verificar_nombre == false) {
            JOptionPane.showMessageDialog(jd_crearHeroe, "Ese nombre del superheroe ya existe eliga otro.");
            crear = false;
            tf_nombreHeroe.setText("");
        }

        if (crear) {
            try {

                Superheroe heroe = new Superheroe(nombre_heroe, poder_heroe, debilidad_heroe, fuerza_heroe,
                        agilidad_fisicaH, agilidad_mentalH);
                lista_nombres.add(nombre_heroe);
                lista_heroes.add(heroe);
                //Agregar a lista
                refrescarListaHeroes();

                JOptionPane.showMessageDialog(jd_crearHeroe, "Se creo exitosamente el heroe.");
                tf_nombreHeroe.setText("");
                tf_poderHeroe.setText("");
                tf_debilidadHeroe.setText("");
                js_fuerzaHeroe.setValue(0);
                js_agilidadMentalHeroe.setValue(0);
                js_agilidadFisicaHeroe.setValue(0);
                jd_crearHeroe.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_crearHeroe, "Ocurrio un error en el sistema.");
            }
        }
    }//GEN-LAST:event_jb_crearHeroeMouseClicked

    private void jb_crearVillanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearVillanoMouseClicked
        //Crear Villano
        String nombre_villano = null, poder_villano = null, debilidad_villano = null;
        int fuerza_villano = 0, agilidad_fisicaV = 0, agilidad_mentalV = 0, suma_statsV = 0;

        boolean crear = true;

        //Validar entradas
        //Nombre
        if (tf_nombreVillano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearVillano, "Falta ingresar el nombre del villano.");
            crear = false;
        } else {
            nombre_villano = tf_nombreVillano.getText();
        }
        //Poder
        if (tf_poderVillano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearVillano, "Falta ingresar el poder del villano.");
            crear = false;
        } else {
            poder_villano = tf_poderVillano.getText();
        }
        //Debilidad Villano
        if (tf_debilidadVillano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearVillano, "Falta ingresar la debilidad del villano.");
            crear = false;
        } else {
            debilidad_villano = tf_debilidadVillano.getText();
        }

        //Datos de estadistica
        //Fuerza
        fuerza_villano = (int) js_fuerzaVillano.getValue();
        //Agilidad Fisica
        agilidad_fisicaV = (int) js_agilidadFisicaVillano.getValue();
        //Agilidad Mental
        agilidad_mentalV = (int) js_agilidadMentalVillano.getValue();

        //Valdiar que las estadisticas sean 100
        suma_statsV = fuerza_villano + agilidad_fisicaV + agilidad_mentalV;

        if (suma_statsV != 100) {
            JOptionPane.showMessageDialog(jd_crearVillano, "Las estadiscticas del villano no igualan a 100.\n"
                    + "No es capaz de ser un villano.");
            crear = false;
            js_fuerzaVillano.setValue(0);
            js_agilidadFisicaVillano.setValue(0);
            js_agilidadMentalVillano.setValue(0);
        }

        //Verificar nombre
        boolean verificar_nombre = true;
        for (int i = 0; i < lista_nombres.size(); i++) {
            if (lista_nombres.contains(nombre_villano)) {
                verificar_nombre = false;
                break;
            }
        }

        if (verificar_nombre == false) {
            JOptionPane.showMessageDialog(jd_crearVillano, "Ese nombre de villano ya existe ingrese otro.");
            crear = false;
        }

        if (crear) {
            try {
                Villano v = new Villano(nombre_villano, poder_villano, debilidad_villano,
                        fuerza_villano, agilidad_fisicaV, agilidad_mentalV);
                //Agregar a listas
                lista_villanos.add(v);
                lista_nombres.add(nombre_villano);
                //Refrescar lista
                refrescarListaVillanos();

                JOptionPane.showMessageDialog(jd_crearVillano, "Se creo el Villano exitosamente!!");
                tf_nombreVillano.setText("");
                tf_poderVillano.setText("");
                tf_debilidadVillano.setText("");
                js_fuerzaVillano.setValue(0);
                js_agilidadFisicaVillano.setValue(0);
                js_agilidadMentalVillano.setValue(0);
                jd_crearVillano.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_crearVillano, "Ocurrio un error en el sistema.");
            }
        }

    }//GEN-LAST:event_jb_crearVillanoMouseClicked

    private void jb_menuVillanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuVillanoMouseClicked

        jd_crearVillano.setModal(true);
        jd_crearVillano.pack();
        jd_crearVillano.setLocationRelativeTo(this);
        jd_crearVillano.setVisible(true);
    }//GEN-LAST:event_jb_menuVillanoMouseClicked

    private void jb_menuEscuadronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuEscuadronMouseClicked

        boolean ingresar_menu = true;
        if (lista_heroes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ningun heroe, debe crear minimo 1.");
            ingresar_menu = false;
        }

        if (lista_villanos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ningun villano debe crear minimo 1.");
            ingresar_menu = false;
        }

        if (ingresar_menu) {
            jd_menuEscuadrones.setModal(true);
            jd_menuEscuadrones.pack();
            jd_menuEscuadrones.setLocationRelativeTo(this);
            jd_menuEscuadrones.setVisible(true);
        }


    }//GEN-LAST:event_jb_menuEscuadronMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre_escuadron = null, lugar_escuadron = null, tipo_escuadron = null;
        boolean crear = true;
        //Validar entrada de datos
        ///Nombre de Escuadron

        if (tf_nombreEscuadron.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Falta el nombre del escuadron.");
            crear = false;
        } else {
            nombre_escuadron = tf_nombreEscuadron.getText();
        }

        //Lugar
        if (tf_lugarEscuadron.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Falta el lugar del escuadron.");
            crear = false;
        } else {
            lugar_escuadron = tf_lugarEscuadron.getText();
        }

        //Tipo de Escuadron
        if (rb_superheroe.isSelected()) {
            tipo_escuadron = "Superheroes";
        } else {
            tipo_escuadron = "Villanos";
        }

        if (crear) {
            try {

                Escuadron e = new Escuadron(nombre_escuadron, lugar_escuadron, tipo_escuadron);
                //Agregar a lista
                lista_escuadrones.add(e);
                //Refrescar lista
                refrescarListaEscuadrones();
                //Agregar al arbol
                JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se creo exitosamente el escuadron.");
                tf_nombreEscuadron.setText("");
                tf_lugarEscuadron.setText("");
                rb_superheroe.setSelected(true);
                rb_villanos.setSelected(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_menuEscuadrones, "Ocurrio un error en el sistema.");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_eliminarEscuadronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarEscuadronMouseClicked
        int pos_elim = jl_listaEscuadrones.getSelectedIndex();

        if (pos_elim >= 0) {
            int resp = JOptionPane.showConfirmDialog(jd_menuEscuadrones, "¿Seguro?", "Eliminar Escuadron", JOptionPane.YES_NO_OPTION);

            if (resp == 0) {
                //Eliminar miembros primero
                Escuadron e_elim = lista_escuadrones.get(pos_elim);

                for (int i = 0; i < e_elim.getLista_miembros().size(); i++) {
                    if (e_elim.getMiembro(i) instanceof Superheroe) {
                        lista_heroes.remove(e_elim.getMiembro(i));
                    } else if (e_elim.getMiembro(i) instanceof Villano) {
                        lista_villanos.remove(e_elim.getMiembro(i));
                    } else {
                        //do nothing
                    }
                }
                //Eliminar Escuadron
                lista_escuadrones.remove(e_elim);
                JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se elimino el escuadron exitosamente!!");
                //Refrescar Listas
                refrescarListaHeroes();
                refrescarListaVillanos();
                refrescarListaEscuadrones();
            } else {
                //do nothing
                //Decidio no eliminar
            }
        } else {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Debe elegir un escuadron!!");
        }

    }//GEN-LAST:event_jb_eliminarEscuadronMouseClicked

    private void jb_modificarEscuadronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarEscuadronMouseClicked
        int pos_modE = jl_listaEscuadrones.getSelectedIndex();

        if (pos_modE >= 0) {
            //Obtener Objeto
            Escuadron e_mod = lista_escuadrones.get(pos_modE);

            tf_nombreEscuadronMod.setText(e_mod.getNombre_escuadron());
            tf_lugarEscuadronMod.setText(e_mod.getLugar_base());

            if (e_mod.getTipo_escuadron().equals("Villanos")) {
                rb_villanosMod.setSelected(true);
            } else {
                rb_villanosMod.setSelected(false);
            }

            jd_modEscuadron.setModal(true);
            jd_modEscuadron.pack();
            jd_modEscuadron.setLocationRelativeTo(jd_menuEscuadrones);
            jd_modEscuadron.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Debe elegir un escuadron!!");
        }
    }//GEN-LAST:event_jb_modificarEscuadronMouseClicked

    private void jb_modEscuadronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modEscuadronMouseClicked

        Escuadron e_mod = lista_escuadrones.get(jl_listaEscuadrones.getSelectedIndex());

        boolean mod = true;
        if (tf_nombreEscuadronMod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modEscuadron, "Al escuadron le falta un nombre");
            mod = false;
        }

        if (tf_lugarEscuadronMod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modEscuadron, "Al escuadron le falta una ubicacion");
            mod = false;
        }

        if (mod) {
            e_mod.setNombre_escuadron(tf_nombreEscuadronMod.getText());
            e_mod.setLugar_base(tf_lugarEscuadronMod.getText());
            if (rb_superheroeMod.isSelected()) {
                e_mod.setTipo_escuadron("Superheroes");
            } else {
                e_mod.setTipo_escuadron("Villanos");
            }
        }

    }//GEN-LAST:event_jb_modEscuadronMouseClicked

    private void jtp_menuEscuadronStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtp_menuEscuadronStateChanged

        if (jtp_menuEscuadron.getSelectedIndex() == 2) {
            if (lista_escuadrones.isEmpty()) {
                JOptionPane.showMessageDialog(jd_menuEscuadrones, "Debe crear minimo 1 escuadron para acceder a esta funcion.");
                jtp_menuEscuadron.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jtp_menuEscuadronStateChanged

    private void jb_elegirLiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elegirLiderMouseClicked

        String salida_heroes = salidaHeroes(), salida_villanos = salidaVillanos();
        if (jl_listaEscuadrones2.getSelectedIndex() >= 0) {
            Escuadron esc = lista_escuadrones.get(jl_listaEscuadrones2.getSelectedIndex());

            if (esc.getLider() == null) {
                JOptionPane.showMessageDialog(jd_menuEscuadrones, "El escuadron ya tiene un lider");
            } else {
                if (esc.getTipo_escuadron().equals("Superheroes")) {
                    //Mostrar salida de heroes
                    int op_liderH = Integer.parseInt(JOptionPane.showInputDialog(jd_menuEscuadrones, "Lista de Heroes\n"
                            + salida_heroes + "Seleccione heroe a hacer lider: "));

                    esc.setLider(lista_heroes.get(op_liderH));
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se eligio al lider del escuadron exitosamente!!");
                } else {
                    //Mostar salida de villanos
                    //Mostrar Opciones
                    int op_liderV = Integer.parseInt(JOptionPane.showInputDialog(jd_menuEscuadrones, "Lista de Villanos\n"
                            + salida_villanos + "Seleccione villano a hacer lider: "));
                    //Set Lider
                    esc.setLider(lista_villanos.get(op_liderV));

                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se eligio al lider del escuadron exitosamente!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Debe elegir un escuadron.");
        }
    }//GEN-LAST:event_jb_elegirLiderMouseClicked

    private void jb_agregarMiembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMiembroMouseClicked

        String salida_heroes = salidaHeroes(), salida_villanos = salidaVillanos();
        if (jl_listaEscuadrones2.getSelectedIndex() >= 0) {
            Escuadron esc = lista_escuadrones.get(jl_listaEscuadrones2.getSelectedIndex());
            //Mostrar heroes o villanos dependiendo del tipo de Escuadron
            if (esc.getTipo_escuadron().equals("Superheroes")) {
                //Agregar Heroe
                int op_miembroAdd = Integer.parseInt(JOptionPane.showInputDialog(jd_menuEscuadrones, "Lista de Superhereos\n"
                        + salida_heroes + "Eliga heroe a agregar: "));

                Superheroe heroe_elegido = lista_heroes.get(op_miembroAdd);

                boolean verificar_miembro = true;
                boolean add_miembro = true;
                for (int i = 0; i < esc.getLista_miembros().size(); i++) {
                    if (esc.getLista_miembros().contains(heroe_elegido)) {
                        verificar_miembro = false;
                        break;
                    }
                }

                if (verificar_miembro == false) {
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "No puede agregar al mismo miembro");
                    add_miembro = false;
                }
                //Comparar si el miembro es igual al lider
                if (esc.getLider() == heroe_elegido) {
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "No puede agregar al lider 2 veces");
                    add_miembro = false;
                }
                if (add_miembro) {
                    esc.setMiembro(heroe_elegido);
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se agrego el miembro exitosamente!!");
                }

            } else {
                //Agregar Villano
                int op_miembroAdd2 = Integer.parseInt(JOptionPane.showInputDialog(jd_menuEscuadrones, "Lista de Villanos\n"
                        + salida_villanos + "Eliga villano a agregar: "));
                Villano v_elegido = lista_villanos.get(op_miembroAdd2);
                boolean add_miembro2 = true;
                boolean verificar_miembro2 = true;
                for (int i = 0; i < esc.getLista_miembros().size(); i++) {
                    if (esc.getLista_miembros().contains(v_elegido)) {
                        verificar_miembro2 = false;
                        break;
                    }
                }

                if (verificar_miembro2 == false) {
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "No puede agregar al mismo miembro");
                    add_miembro2 = false;
                }
                //Comparar si el miembro es igual al lider
                if (esc.getLider() == v_elegido) {
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "No puede agregar al lider 2 veces");
                    add_miembro2 = false;
                }

                if (add_miembro2) {
                    esc.setMiembro(v_elegido);
                    JOptionPane.showMessageDialog(jd_menuEscuadrones, "Se agrego el miembro exitosamente!!");
                }

            }

        } else {
            JOptionPane.showMessageDialog(jd_menuEscuadrones, "Debe elegir un escuadron.");
        }
    }//GEN-LAST:event_jb_agregarMiembroMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_tipoEscuadron;
    private javax.swing.ButtonGroup bg_tipoEscuadronMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jb_agregarMiembro;
    private javax.swing.JButton jb_crearHeroe;
    private javax.swing.JButton jb_crearVillano;
    private javax.swing.JButton jb_elegirLider;
    private javax.swing.JButton jb_eliminarEscuadron;
    private javax.swing.JButton jb_menuEscuadron;
    private javax.swing.JButton jb_menuHeroe;
    private javax.swing.JButton jb_menuVillano;
    private javax.swing.JButton jb_modEscuadron;
    private javax.swing.JButton jb_modificarEscuadron;
    private javax.swing.JButton jb_simulacion;
    private javax.swing.JDialog jd_crearHeroe;
    private javax.swing.JDialog jd_crearVillano;
    private javax.swing.JDialog jd_menuEscuadrones;
    private javax.swing.JDialog jd_modEscuadron;
    private javax.swing.JList<String> jl_listaEscuadrones;
    private javax.swing.JList<String> jl_listaEscuadrones2;
    private javax.swing.JList<String> jl_listaHeroes;
    private javax.swing.JList<String> jl_listaVillanos;
    private javax.swing.JSpinner js_agilidadFisicaHeroe;
    private javax.swing.JSpinner js_agilidadFisicaVillano;
    private javax.swing.JSpinner js_agilidadMentalHeroe;
    private javax.swing.JSpinner js_agilidadMentalVillano;
    private javax.swing.JSpinner js_fuerzaHeroe;
    private javax.swing.JSpinner js_fuerzaVillano;
    private javax.swing.JTabbedPane jtb_menuHeroe;
    private javax.swing.JTabbedPane jtp_menuEscuadron;
    private javax.swing.JRadioButton rb_superheroe;
    private javax.swing.JRadioButton rb_superheroeMod;
    private javax.swing.JRadioButton rb_villanos;
    private javax.swing.JRadioButton rb_villanosMod;
    private javax.swing.JTextField tf_debilidadHeroe;
    private javax.swing.JTextField tf_debilidadVillano;
    private javax.swing.JTextField tf_lugarEscuadron;
    private javax.swing.JTextField tf_lugarEscuadronMod;
    private javax.swing.JTextField tf_nombreEscuadron;
    private javax.swing.JTextField tf_nombreEscuadronMod;
    private javax.swing.JTextField tf_nombreHeroe;
    private javax.swing.JTextField tf_nombreVillano;
    private javax.swing.JTextField tf_poderHeroe;
    private javax.swing.JTextField tf_poderVillano;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> lista_nombres = new ArrayList();
    ArrayList<Superheroe> lista_heroes = new ArrayList();
    ArrayList<Villano> lista_villanos = new ArrayList();
    ArrayList<Escuadron> lista_escuadrones = new ArrayList();

    public void refrescarListaHeroes() {
        DefaultListModel model = new DefaultListModel();

        for (Superheroe h : lista_heroes) {
            model.addElement(h);
        }
        jl_listaHeroes.setModel(model);
    }

    public void refrescarListaVillanos() {
        DefaultListModel model = new DefaultListModel();

        for (Villano v : lista_villanos) {
            model.addElement(v);
        }
        jl_listaVillanos.setModel(model);
    }

    public void refrescarListaEscuadrones() {
        DefaultListModel model = new DefaultListModel();

        for (Escuadron e : lista_escuadrones) {
            model.addElement(e);
        }

        jl_listaEscuadrones.setModel(model);
        jl_listaEscuadrones2.setModel(model);
    }

    public String salidaHeroes() {
        String salida_heroes = "";
        for (int i = 0; i < lista_heroes.size(); i++) {
            Superheroe s = lista_heroes.get(i);
            salida_heroes += "[" + i + "] Nombre: " + s.getNombre() + ", Poder: " + s.getPoder()
                    + ", Debilidad:" + s.getDebilidad() + ", Fuerza: " + s.getFuerza()
                    + ", Agilidad Fisica: " + s.getAgilidad_fisica() + ", Agilidad Mental: " + s.getAgilidad_mental() + "\n";
        }
        return salida_heroes;
    }

    public String salidaVillanos() {

        String salida_villanos = "";
        for (int i = 0; i < lista_villanos.size(); i++) {
            Villano v = lista_villanos.get(i);
            salida_villanos += "[" + i + "] Nombre: " + v.getNombre() + ", Poder: " + v.getPoder()
                    + ", Debilidad:" + v.getDebilidad() + ", Fuerza: " + v.getFuerza()
                    + ", Agilidad Fisica: " + v.getAgilidad_fisica() + ", Agilidad Mental: " + v.getAgilidad_mental() + "\n";
        }

        return salida_villanos;
    }

}
